### ISSUE TITLE
Warnings?

### ISSUE THREAD

**Issue by argonan0** [3ventic/discord-rss#9]
```
npm run sync

> discorss@0.11.0 sync
> svelte-kit sync

(node:278069) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
(node:278069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:278069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 3ventic** [comment]
cannot repro, are you using supported versions of node/npm?

**Comment by 3ventic** [comment]
I would recommend using https://github.com/nvm-sh/nvm

**Comment by 3ventic** [comment]
did you upgrade any dependencies from what's defined in the main branch right now? I know there are some breaking changes to sveltekit's config from the prerelease version that was used for this and I haven't felt the urge to upgrade it yet.
